language: node_js
node_js:
- '0.12'
sudo: required
dist: precise
group: edge
env:
  global:
  - CF_APP=deployment-tracker
  - CF_API=https://api.ng.bluemix.net
  - CF_ORGANIZATION=Dev-Advocates
  - CF_SPACE=metrics
  - secure: "hojP3lVKblVWKC7KDqMoEvabVPm0RxDKUSfN+KQX9COScBvqUx20aQEFC1coSO3Mn30Tzzg3nxEzNcCe8r9NPOdrAULUDvzpZwT7iijug5Ftval/637E90MMevS6HOPM8+devo1B8juuNLV4H0qXco+g2yKVWhSyGZ7qP+1/Qmw="
  - secure: "T+xElY7tZwn8ntZyndYhCZ6K4vdPRVgVb1AsBD/jje2mySSfFqtqOVpiB/M4DXIP8XL+l4U2J2y2272xu2b4WaXFCKwtj+ipaGWJHBUtvkreHdu5cTygOxRsN+vBUdvSr3cXugMpu9mSFooIAwflYI9Jbs/7PPuBm5ZiI2a+oPY="
before_deploy: npm install -g cf-blue-green
deploy:
  provider: script
  script: cf-blue-green-travis
  on:
    branch: master
    repo: IBM-Bluemix/cf-deployment-tracker-service
notifications:
  slack:
    secure: fX/TSQVQ0MWj6IhmW8hb0ulVgmDadDGP+mjEaBvYfQbLhHUzB67iZl0+EFAoYBi44yyR8Ja1N2D27tcxrsoaeaFiWRBZL6Ri5IzWw/cyI61CEjp/4xj5YzBFqU/4KYcibBgH3kX3JltXuJnXtjJweeDGEe4ZPCbTGgC73csrvug=
