language: node_js
node_js:
- '0.12'
sudo: true
env:
  global:
  - CF_APP=[deployment-tracker]
  - CF_API=[https://api.ng.bluemix.net]
  - secure: "jYzrHECNACiBCBg1L9rYhXCWtKex6n5EA3tqOxHM8xauEwMj+VX1uM0srdSEhg4kJlCOuT2rwc9w2eWEO+8rFl2i2AAl2Lljs80S4PEvT4KsirnidGeVHnEoSaY32DGmGC0tEUv4hN4jOISAFuclCp8EARic9pWkp4PbA8kMWOE="
  - CF_ORGANIZATION=[Dev-Advocates]
  - CF_SPACE=[metrics]
  - secure: "KA1RTclMUNM8UJ4rv3T6OWYH73LA8Ga2aJeYlDJ65HvcvVCZemGpyXoAZHsMYBbFxqo96Vkfm/hgjRXT2A2Jkw8UWMaQScFFYiNpZP10C22t4qWS9tdl7WoxBmO5VF9waOEm6mg944J4G3BOh8hn7dA/LxUnZqPov+AljK2AXsc="
before_deploy: npm install -g cf-blue-green
deploy:
  provider: script
  script: cf-blue-green-travis
  on:
    branch: master
    repo: IBM-Bluemix/cf-deployment-tracker-service
