language: node_js
node_js:
- '0.12'
sudo: required
dist: precise
group: edge
env:
  global:
  - CF_APP=deployment-tracker
  - CF_API=https://api.ng.bluemix.net
  - CF_ORGANIZATION=Dev-Advocates
  - CF_SPACE=metrics
  - secure: fBh5oYlsuJgQ0KrrVY8EUuY2F3aDpjxaNI6CE+EAQREoDYArb0GPYEz4uYpkVDqSpRE3XpgqJjVlcGd2M3WXOA9fmT+T7qTKVWO9ZPKvNAwxTxLN4PCMp/8K6LeEH31Ax/SpnB9rAPdVvQUJ4WKZkr7kdlWrFVAuSpqnZKevpmM=
  - secure: QD8s2/p+sav2D+QX8Z9a1E4yxijn3E7FngUuC1z9a0Nots9GyM/EzQNGle7DRUIVDv3XQvOLLEc4D1OZJTM8t8eR6PP7sP7K0PKLnAE7i12RETZl60yHX95uuIvcnUGhhfrM0WeG8jof8e3j91GXyP5qptWbOL8tIdtW+Y6AuHo=
before_deploy: npm install -g cf-blue-green
deploy:
  provider: script
  script: cf-blue-green-travis
  on:
    branch: master
    repo: IBM-Bluemix/cf-deployment-tracker-service
notifications:
  slack:
    secure: MCvsL/ElMeUUPJNK+WmRsI1khA7wDw59e/JX7G5saQ2XKsJd0WleqYnModjmfZVvKVPBWGTsZrOthedW/YGBSSeaBzS+lOpIt+9TZsVugyEZ89yEisL8Q+pzq/Ym43d4+ELiIiKdpDkq4UDbl9SjiDqbC+yxlXtCA7HHrlSD6kE=
